lib/elixir_blog_web/router.ex
defmodule ElixirBlogWeb.Router do
  use ElixirBlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ElixirBlogWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/articles", ArticleController do
      resources "/comments", CommentController, except: [:edit, :update]
    end
    resources "/users", UserController
  end

  # Other scopes may use custom stacks.
  # scope "/api", ElixirBlogWeb do
  #   pipe_through :api
  # end
end

lib/elixir_blog/comments/comment.ex
defmodule ElixirBlog.Comments.Comment do
  use Ecto.Schema
  import Ecto.Changeset
  alias ElixirBlog.Comments.Comment


  schema "comments" do
    field :body, :string
    field :title, :string
    field :user_id, :integer
    belongs_to :article, ElixirBlog.Posts.Article

    timestamps()
  end

  @doc false
  def changeset(%Comment{} = comment, attrs) do
    comment
    |> cast(attrs, [:title, :body, :article_id, :user_id])
    |> validate_required([:title, :body, :article_id])
  end
end

lib/elixir_blog/comments/comments.ex
defmodule ElixirBlog.Comments do
  @moduledoc """
  The Comments context.
  """

  import Ecto.Query, warn: false
  alias ElixirBlog.Repo

  alias ElixirBlog.Comments.Comment

  @doc """
  Returns the list of comments.

  ## Examples

      iex> list_comments(article)
      [%Comment{}, ...]

  """
  def list_comments(article) do
    Comment
    |> where([c], c.article_id == ^article.id)
    |> Repo.all
  end

  @doc """
  Gets a single comment.

  Raises `Ecto.NoResultsError` if the Comment does not exist.

  ## Examples

      iex> get_comment!(article, 123)
      %Comment{}

      iex> get_comment!(article, 456)
      ** (Ecto.NoResultsError)

  """
  def get_comment!(article, id) do
    Comment
    |> where([c], c.article_id == ^article.id)
    |> Repo.get!(id)
  end

  @doc """
  Creates a comment.

  ## Examples

      iex> create_comment(%{field: value})
      {:ok, %Comment{}}

      iex> create_comment(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_comment(attrs \\ %{}) do
    %Comment{}
    |> Comment.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a comment.

  ## Examples

      iex> update_comment(comment, %{field: new_value})
      {:ok, %Comment{}}

      iex> update_comment(comment, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_comment(%Comment{} = comment, attrs) do
    comment
    |> Comment.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Comment.

  ## Examples

      iex> delete_comment(comment)
      {:ok, %Comment{}}

      iex> delete_comment(comment)
      {:error, %Ecto.Changeset{}}

  """
  def delete_comment(%Comment{} = comment) do
    Repo.delete(comment)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking comment changes.

  ## Examples

      iex> change_comment(comment)
      %Ecto.Changeset{source: %Comment{}}

  """
  def change_comment(%Comment{} = comment) do
    Comment.changeset(comment, %{})
  end
end

lib/elixir_blog_web/controllers/comment_controller.ex
defmodule ElixirBlogWeb.CommentController do
  use ElixirBlogWeb, :controller

  alias ElixirBlog.Comments
  alias ElixirBlog.Comments.Comment

  def action(conn, _) do
    article = ElixirBlog.Posts.get_article!(conn.params["article_id"])
    args = [conn, conn.params, article]
    apply(__MODULE__, action_name(conn), args)
  end

  def index(conn, _params, article) do
    comments = Comments.list_comments(article)
    render(conn, "index.html", comments: comments, article: article)
  end

  def new(conn, _params, article) do
    changeset =
    %Comment{article_id: article.id}
    |> Comments.change_comment
    render(conn, "new.html", changeset: changeset, article: article)
  end

  def create(conn, %{"comment" => comment_params}, article) do
    comment_params =
      comment_params
      |> Map.put("article_id", article.id)

    case Comments.create_comment(comment_params) do
      {:ok, _comment} ->
        conn
        |> put_flash(:info, "Comment created successfully.")
        |> redirect(to: article_path(conn, :show, article))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset, article: article)
    end
  end

  def show(conn, %{"id" => id}, article) do
    comment = Comments.get_comment!(article, id)
    render(conn, "show.html", comment: comment, article: article)
  end

  def edit(conn, %{"id" => id}, article) do
    comment = Comments.get_comment!(article, id)
    changeset = Comments.change_comment(comment)
    render(conn, "edit.html", comment: comment, article: article, changeset: changeset)
  end

  def update(conn, %{"id" => id, "comment" => comment_params}, article) do
    comment = Comments.get_comment!(article, id)

    case Comments.update_comment(comment, comment_params) do
      {:ok, _comment} ->
        conn
        |> put_flash(:info, "Comment updated successfully.")
        |> redirect(to: article_path(conn, :show, article))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", comment: comment, article: article, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}, article) do
    comment = Comments.get_comment!(article, id)
    {:ok, _comment} = Comments.delete_comment(comment)

    conn
    |> put_flash(:info, "Comment deleted successfully.")
    |> redirect(to: article_path(conn, :show, article))
  end
end

lib/elixir_blog_web/views/comment_view.ex
defmodule ElixirBlogWeb.CommentView do
  use ElixirBlogWeb, :view
end

lib/elixir_blog_web/templates/comment/edit.html.eex
<h2>Edit Comment</h2>

<%= render "form.html", Map.put(assigns, :action, article_comment_path(@conn, :update, @article, @comment)) %>

<span><%= link "Back", to: article_comment_path(@conn, :index, @article) %></span>

lib/elixir_blog_web/templates/comment/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :body, class: "control-label" %>
    <%= textarea f, :body, class: "form-control" %>
    <%= error_tag f, :body %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/elixir_blog_web/templates/comment/index.html.eex
<h4>Comments</h4>
<%= for comment <- @comments do %>
    <h5><%= comment.title %></h5>
    <%= text_to_html comment.body %>

    <span><%= link "Delete", to: article_comment_path(@conn, :delete, @article, comment), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
<% end %>

lib/elixir_blog_web/templates/comment/new.html.eex
<h2>New Comment</h2>

<%= render "form.html", Map.put(assigns, :action, article_comment_path(@conn, :create, @article)) %>

lib/elixir_blog_web/templates/comment/show.html.eex
<h2>Show Comment</h2>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @comment.title %>
  </li>

  <li>
    <strong>Body:</strong>
    <%= @comment.body %>
  </li>

  <li>
    <strong>Article:</strong>
    <%= @comment.article_id %>
  </li>

  <li>
    <strong>User:</strong>
    <%= @comment.user_id %>
  </li>

</ul>

<span><%= link "Back", to: article_comment_path(@conn, :index, @article) %></span>